;-----------[STANDARD GRAPHIC ADAPTER MODES]--------------------
;Declaration of standard video modes RAM area needed.

silicium_videomodes:
vidmode00:      dd      0       ,       0
vidmode01:      dd      0       ,       0
vidmode02:      dd      0       ,       0
vidmode03:      dd      4000    ,       0xB8000
vidmode04:      dd      0       ,       0
vidmode05:      dd      0       ,       0
vidmode06:      dd      0       ,       0
vidmode07:      dd      0       ,       0
vidmode08:      dd      0       ,       0
vidmode09:      dd      0       ,       0
vidmode0A:      dd      0       ,       0
vidmode0B:      dd      0       ,       0
vidmode0C:      dd      0       ,       0
vidmode0D:      dd      32000   ,       0xA0000
vidmode0E:      dd      64000   ,       0xA0000
vidmode0F:      dd      28000   ,       0xA0000
vidmode10:      dd      0       ,       0
vidmode11:      dd      38400   ,       0xA0000
vidmode12:      dd      153600  ,       0xA0000
vidmode13:      dd      64000   ,       0xA0000
