;%define int.disable_nmi.VID 31
;%define int.enable_nmi.VID 30
;%define int.get_irq_mask.VID 36
;%define int.hook.VID 39
;%define int.hook_irq.VID 32
;%define int.mask_irq.VID 34
;%define int.set_default_handler.VID 173
;%define int.set_irq_mask.VID 37
;%define int.unhook.VID 174
;%define int.unhook_irq.VID 33
;%define int.unmask_irq.VID 35

%define int.set_handler.VID 39
%define int.unset_handler.VID 174
