; $Header: /cvsroot/uuu/uuu/src/apps/games/ttt/pcx/sizes.inc,v 1.1 2001/10/26 17:17:39 daboy Exp $

%define RECTSIZE	32
%define PIECESIZE	32
%define BORDERSIZE	32
%define WINSSIZEX	100
%define WINSSIZEY	32
%define RESTARTSIZEX	320
%define RESTARTSIZEY	32
%define REDSIZEX	64
%define REDSIZEY	32
%define BLUESIZEX	80
%define BLUESIZEY	32

%define TURNSIZEX	64
%define TURNSIZEY	64

%define DRAWSIZEX	128
%define DRAWSIZEY	32
