%define pci.list_vendor_devices.VID 111
%define pci.list_class_code_devices.VID 112 
%define pci.generate_special_cycle.VID 113
%define pci.get_interrupt_routing_options.VID 114
%define pci.read_configuration_byte.VID 115
%define pci.read_configuration_word.VID 116
%define pci.read_configuration_dword.VID 117
%define pci.write_configuration_byte.VID 118
%define pci.write_configuration_word.VID 119
%define pci.write_configuration_dword.VID 120

