; Unununium Standard Libs		by Lukas Demetz
; STDIO, Formatted I/O
;
; Description: Provides FS interface to UUU
;
;
; Status: Coding

global fprintf
global fscanf
global printf
global scanf
global sprintf
global sscanf
global vfprintf
global vprintf
global vsprintf
global fgetc
global fgets
global fputc
global fputs
global getc
global getchar
global gets
global putc
global putchar
global puts
global ungetc 
global perror 
